version: '2.1'

services:
  webhulk:
    build: .
    command: go run main.go server
    ports:
      - "8080:8080"
    volumes:
      - ./:/go/src/github.com/grvcoelho/webhulk
    depends_on:
      - database

  database:
    image: postgres:9.6-alpine
    ports:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webhulk
